### PR TITLE
Refactor user.ex

### PR DESCRIPTION
**Pull request by wuhkuh**
1) user.ex contains some code that could be simplified using pattern matching, as well as some chunks which could be extracted into their own functions.
2) There are also instances of hard-coded values such as the mapping of `Encryption.Hashfield` to the `:email` atom, where a dynamic approach could be used; we could check if the type implements `dump/1` and invoke it if necessary.
3) Finally, it defines an unused `Util` module.

This PR refactors/fixes all of the aforementioned 'issues':

1) `prepare_fields/1` is now split into two functions, based on changeset validity. A new function has been added, which determines whether the field is of a custom type.
2) Hard-coded values are now removed and `is_custom_type?/2` has been implemented, which checks if the field implements `dump/1`. Field source mapping can now be done through a module attribute: `@field_source_map`.
3) The unused `Util` module has been removed.

Feedback is very welcome.

### CODE REVIEW

**Comment by wuhkuh** [comment]
After more code review, it appears that I can compress this code into one functional block. Commit will follow shortly.

**Comment by wuhkuh** [comment]
Tests seem to be failing because of a lacking .env file.
This in turn causes `System.get_env("ENCRYPTION_KEYS")` to be `nil`, followed by failure of `String.replace/2`.

**Comment by nelsonic** [comment]
@wuhkuh we're excited about this PR as simplifying code is great!

Tests pass on `master` without an `.env` file:
https://travis-ci.org/dwyl/phoenix-ecto-encryption-example/builds/462490897#L621

The `ENCRYPTION_KEYS` are defined as environment variables on Travis-CI:
image

**Comment by wuhkuh** [comment]
The failing build is caused by a safety precaution made by the Travis-CI team.
See: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by wuhkuh** [comment]
This is probably as clean as it gets. I could squash and rebase the commits after the environment variable issue is sorted.

**Comment by nelsonic** [comment]
@wuhkuh thanks for reminding us of the Travis-CI security restriction.
I've invited you to be a collaborator on this repo 
https://github.com/dwyl/phoenix-ecto-encryption-example/invitations
so you can push your branch directly to the repo and the PR should pass on Travis.

**Review by nelsonic — APPROVED** [review]
@wuhkuh thanks for making these updates. 🙌 
I have resolved the outstanding **`merge-conflicts`**. ✅ 
Merging. :shipit:

**Pull request merged**
